In [24]:
import numpy as np

In [25]:
arr = np.random.randint(1,10,(4,4))

In [26]:
arr

array([[2, 5, 6, 5],
       [8, 4, 1, 1],
       [7, 3, 3, 9],
       [3, 2, 6, 7]])

In [27]:
arr.reshape(8,2)

array([[2, 5],
       [6, 5],
       [8, 4],
       [1, 1],
       [7, 3],
       [3, 9],
       [3, 2],
       [6, 7]])

In [28]:
arr

array([[2, 5, 6, 5],
       [8, 4, 1, 1],
       [7, 3, 3, 9],
       [3, 2, 6, 7]])

In [29]:
arr.T

array([[2, 8, 7, 3],
       [5, 4, 3, 2],
       [6, 1, 3, 6],
       [5, 1, 9, 7]])

In [30]:
arr.flatten()

array([2, 5, 6, 5, 8, 4, 1, 1, 7, 3, 3, 9, 3, 2, 6, 7])

In [31]:
np.expand_dims(arr)
## error

TypeError: expand_dims() missing 1 required positional argument: 'axis'

In [ ]:
np.expand_dims(arr,axis=1)

array([[[7, 3, 3, 7]],

       [[6, 8, 6, 3]],

       [[7, 1, 2, 5]],

       [[9, 3, 9, 9]]])

In [ ]:
data=np.array([1,2,3,4])

In [ ]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])

In [ ]:
np.roll(data,2)

array([3, 4, 1, 2])

In [ ]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
##numpy binary operation
arr1 = np.random.randint(1,10,(3,4))

In [ ]:
arr2=np.random.randint(1,10,(3,4))

In [ ]:
arr1

NameError: name 'arr1' is not defined

In [ ]:
arr2

array([[7, 2, 1, 4],
       [4, 1, 1, 7],
       [1, 2, 6, 8]])

In [ ]:
arr1 + arr2

array([[16,  5, 10,  8],
       [10,  3,  7,  8],
       [10,  3,  9, 10]])

In [ ]:
arr1 * arr2

array([[63,  6,  9, 16],
       [24,  2,  6,  7],
       [ 9,  2, 18, 16]])

In [ ]:
arr1 /arr2

array([[1.28571429, 1.5       , 9.        , 1.        ],
       [1.5       , 2.        , 6.        , 0.14285714],
       [9.        , 0.5       , 0.5       , 0.25      ]])

In [ ]:
arr1 - arr2

array([[ 2,  1,  8,  0],
       [ 2,  1,  5, -6],
       [ 8, -1, -3, -6]])

In [ ]:
arr1 ** arr2

array([[4782969,       9,       9,     256],
       [   1296,       2,       6,       1],
       [      9,       1,     729,     256]])

In [32]:
~arr1

TypeError: bad operand type for unary ~: 'list'

In [ ]:
arr1 > arr2

NameError: name 'arr2' is not defined

In [ ]:
## numpy String function
arr=np.array(["silki","santo"])
arr

array(['silki', 'santo'], dtype='<U5')

In [ ]:
np.char.upper(arr)

TypeError: string operation on non-string array

In [ ]:
np.char.title(arr)

array(['Silki', 'Santo'], dtype='<U5')

In [ ]:
np.char.capitalize(arr)

TypeError: string operation on non-string array

In [ ]:
np.char.lower(arr)

array(['silki', 'santo'], dtype='<U5')

In [ ]:
#Numpy -Mathematical funtion
arr1=[1,2,5,3]
np.sin(arr1)

array([ 0.84147098,  0.90929743, -0.95892427,  0.14112001])

In [33]:
np.cos(arr1)

array([ 0.54030231, -0.41614684,  0.28366219, -0.9899925 ])

In [34]:
np.tan(arr1)

array([ 1.55740772, -2.18503986, -3.38051501, -0.14254654])

In [35]:
np.log10(arr1)

array([0.        , 0.30103   , 0.69897   , 0.47712125])

In [36]:
np.exp(arr1)

array([  2.71828183,   7.3890561 , 148.4131591 ,  20.08553692])

In [38]:
np.power(arr1,2)

array([ 1,  4, 25,  9], dtype=int32)

In [39]:
np.mean(arr1)

2.75

In [40]:
np.median(arr1)

2.5

In [41]:
np.mode(arr1)

AttributeError: module 'numpy' has no attribute 'mode'

In [42]:
np.std(arr1)

1.479019945774904

In [43]:
np.var(arr1)

2.1875

In [44]:
np.min(arr1)

1

In [45]:
np.max(arr1)

5

In [47]:
arr2=[4,8,9,7]

In [48]:
## numpy arithmatic operation
np.subtract(arr1,arr2)

array([-3, -6, -4, -4])

In [51]:
arr2-arr1

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [52]:
np.multiply(arr1,arr2)

array([ 4, 16, 45, 21])

In [53]:
np.mod(arr1,arr2)

array([1, 2, 5, 3])

In [54]:
np.power(arr1,arr2)

array([      1,     256, 1953125,    2187])

In [55]:
# numpy staticscial function
np.mean(arr1)

2.75

In [56]:
np.median(arr1)

2.5

In [57]:
#sort ,serach and counting function
import numpy as np

In [58]:
arr=np.array([4,2,8,5,3,12,56])
arr

array([ 4,  2,  8,  5,  3, 12, 56])

In [59]:
np.sort(arr)

array([ 2,  3,  4,  5,  8, 12, 56])

In [61]:
np.searchsorted(arr,4)

2

In [62]:
arr1=np.array([0,354,45,23,56,895,756,856,845])


In [63]:
np.count_nonzero(arr1)

8

In [64]:
np.where(arr >0)

(array([0, 1, 2, 3, 4, 5, 6], dtype=int64),)

In [65]:
np.extract(arr1 > 2,arr1)

array([354,  45,  23,  56, 895, 756, 856, 845])

In [66]:
## numpy - Byte swapping
arr1

array([  0, 354,  45,  23,  56, 895, 756, 856, 845])

In [67]:
arr.byteswap()

array([ 67108864,  33554432, 134217728,  83886080,  50331648, 201326592,
       939524096])

In [68]:
arr

array([ 4,  2,  8,  5,  3, 12, 56])

In [69]:
arr

array([ 4,  2,  8,  5,  3, 12, 56])

In [75]:
##numpy - Copies and views
a= np.copy(arr1)

In [76]:
b= arr1.view()
b

array([234, 354,  45,  23,  56, 895, 756, 856, 845])

In [79]:
b[0]=23

In [80]:
b

array([ 23, 354,  45,  23,  56, 895, 756, 856, 845])

In [81]:
arr1

array([ 23, 354,  45,  23,  56, 895, 756, 856, 845])

In [82]:
#numpy- Matrix LIbrayr
import numpy.matlib as nm

In [83]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [84]:
nm.ones(7)

matrix([[1., 1., 1., 1., 1., 1., 1.]])

In [86]:
nm.eye(4 )

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [110]:
## numpy - linear algebra
arr1 = np.random.randint([[2,3],[4,5]])

In [111]:
arr1

array([[0, 1],
       [2, 2]])

In [112]:
arr2

array([[16,  3],
       [10, 25]])

In [113]:
arr1

array([[0, 1],
       [2, 2]])

In [114]:
arr2

array([[16,  3],
       [10, 25]])

In [106]:
arr2 = np.random.randint([[22,13],[14,55]])

In [115]:
arr2

array([[16,  3],
       [10, 25]])

In [116]:
arr1@arr2

array([[10, 25],
       [52, 56]])

In [117]:
np.dot(arr1,arr2)

array([[10, 25],
       [52, 56]])