In [3]:
import numpy as np
l = [1,2,3,4,5]
array=np.array(l)
type(array)

numpy.ndarray

In [4]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [5]:
arr1 = np.array([[1,2,3],[4,5,6]])
array.ndim

1

In [6]:
arr1.ndim

2

In [7]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
array

array([1, 2, 3, 4, 5])

In [9]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
np.matrix(l)

matrix([[1, 2, 3, 4, 5]])

In [11]:
## asanyarray function convert the input data into the array.
mat = np.matrix(l)
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [12]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [13]:
a = array
a

array([1, 2, 3, 4, 5])

In [14]:
array

array([1, 2, 3, 4, 5])

In [15]:
array[0]=100
array

array([100,   2,   3,   4,   5])

In [16]:
a

array([100,   2,   3,   4,   5])

In [17]:
b = np.copy(array)
b
#The copy ( ) return a shllow copy of the list , and deepcopy () return a deep copy of list .

array([100,   2,   3,   4,   5])

In [18]:
b[0] =347965
b
# This is the shallow copy in which the change in b will not affect the array

array([347965,      2,      3,      4,      5])

In [19]:
array

array([100,   2,   3,   4,   5])

In [20]:
np.fromfunction(lambda i, j:i ==j ,(3,3))
# formfunction --> formfunction is a function in python which is used to construct an array in such a way that a given function passed to it exceuted

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [21]:
np.fromfunction(lambda i, j:i*j ,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [22]:
(i*i for i in range (5))

<generator object <genexpr> at 0x0000020DC2CCDF20>

In [23]:
list (i* i for i in range (5))

[0, 1, 4, 9, 16]

In [24]:
iterable = (list (i* i for i in range (5)))
np.fromiter(iterable , float)

array([ 0.,  1.,  4.,  9., 16.])

In [25]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
array.ndim

1

In [27]:
np.fromstring('23 45 56 ',sep = ' ')

array([23., 45., 56.])

In [28]:
arr1 .ndim

2

In [29]:
array.size

5

In [30]:
arr1.size

6

In [31]:
arr1.shape

(2, 3)

In [32]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
arr1.dtype

dtype('int32')

In [34]:
array.dtype

dtype('int32')