In [1]:
import numpy as np

In [2]:
list(range(5))

[0, 1, 2, 3, 4]

In [4]:
# ERROR WILL COME
list (range(0.4,10.4))

TypeError: 'float' object cannot be interpreted as an integer

In [9]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [11]:
#the numpy.logspace()function returns number space evenly w.r.t. interval on  log scale.
np.logspace(1,5,10,base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((3,5,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [17]:
np.zeros((1,2))

array([[0., 0.]])

In [18]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
l=[1,2,3,4,5]
arr = np.array(l)


In [22]:
arr+5

array([ 6,  7,  8,  9, 10])

In [23]:
arr*4

array([ 4,  8, 12, 16, 20])

In [24]:
np.empty((3,4))

array([[7.55568555e-312, 2.47032823e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.10343781e-312, 2.92966904e-033, 7.17593402e-091,
        2.36053162e+180],
       [1.56091988e+184, 2.61897213e+180, 3.99910963e+252,
        1.90979636e-312]])

In [27]:
## give identical matrix
arr1=np.eye(5)
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
import pandas as pd

In [29]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [30]:
np.random.rand(2,3)

array([[0.46964858, 0.35885463, 0.6031451 ],
       [0.06653386, 0.41913324, 0.79886497]])

In [33]:
np.random.randint(1,5,(3,4))

array([[1, 4, 3, 3],
       [4, 3, 4, 3],
       [3, 2, 1, 1]])

In [34]:
arr1.size

25

In [35]:
arr1.shape

(5, 5)

In [42]:
arr1[2:4,[2,3]]

array([[1., 0.],
       [0., 1.]])

In [43]:
arr1=np.random.randint(1,3,(2,3))

In [44]:
arr1

array([[1, 2, 2],
       [2, 1, 2]])

In [46]:
## Numpy Broadcasting
arr=np.zeros((3,4))

In [47]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [48]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [53]:
a=np.array([1,2,3,4])
arr = a
arr

array([1, 2, 3, 4])

In [54]:
b=np.array([3,4,5])
arr1 = b.T
arr1

array([3, 4, 5])

In [55]:
b.T

array([3, 4, 5])

In [56]:
np.sqrt(arr1)

array([1.73205081, 2.        , 2.23606798])

In [57]:
np.log10(arr1)

array([0.47712125, 0.60205999, 0.69897   ])

In [58]:
np.exp(arr1)

array([ 20.08553692,  54.59815003, 148.4131591 ])

In [59]:
np.min(arr1)

3

In [60]:
np.max(arr1)

5