In [1]:
import pandas as pd
list (range(5))

[0, 1, 2, 3, 4]

In [2]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
#list(range(0,4,10.1))
#Note range function will give error because it take int values
import numpy as np
np.arange(0.4,10.1)

array([0.4, 1.4, 2.4, 3.4, 4.4, 5.4, 6.4, 7.4, 8.4, 9.4])

In [4]:
list (np.arange(0.4,10.1,0.2))

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002,
 5.400000000000002,
 5.600000000000002,
 5.8000000000000025,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.8000000000000025,
 8.000000000000002,
 8.200000000000003,
 8.400000000000004,
 8.600000000000003,
 8.800000000000002,
 9.000000000000004,
 9.200000000000003,
 9.400000000000004,
 9.600000000000003,
 9.800000000000004,
 10.000000000000004]

In [5]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [6]:
np.logspace(1,5,20)

array([1.00000000e+01, 1.62377674e+01, 2.63665090e+01, 4.28133240e+01,
       6.95192796e+01, 1.12883789e+02, 1.83298071e+02, 2.97635144e+02,
       4.83293024e+02, 7.84759970e+02, 1.27427499e+03, 2.06913808e+03,
       3.35981829e+03, 5.45559478e+03, 8.85866790e+03, 1.43844989e+04,
       2.33572147e+04, 3.79269019e+04, 6.15848211e+04, 1.00000000e+05])

In [7]:
np.logspace(1,5,10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [8]:
np.logspace(1,5,10,base=2)
# The numpy.logspace() function return number space evenly w.r.t interval on a log scale.The numpy .logspace() function return number spacce even

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.zeros((3,10,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [12]:
np.zeros((3,10,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0.,

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
arr = np.ones((3,10))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [15]:
arr + 5

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.]])

In [16]:
arr * 4

array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

In [18]:
arr ** 10

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [19]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
arr1 = np.eye(5)
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [23]:
np.random.rand(3,4)

array([[0.70306064, 0.24201817, 0.26359924, 0.96317965],
       [0.18663837, 0.74726337, 0.47675722, 0.34285052],
       [0.66385914, 0.07089309, 0.09974822, 0.06376526]])

In [25]:
np.random.rand(3,4)

array([[0.11946673, 0.90543332, 0.26554221, 0.85246297],
       [0.62916551, 0.96450756, 0.38681864, 0.69550187],
       [0.15799497, 0.9084498 , 0.52876225, 0.29796788]])

In [27]:
np.random.randint(1,5,(3,4))

array([[2, 4, 3, 2],
       [3, 4, 4, 1],
       [1, 1, 3, 4]])

In [28]:
arr2 = np.random.randint(1,5,(3,4))
arr2.size

12

In [29]:
arr2.shape

(3, 4)

In [30]:
arr2.reshape(6,2)
# note if we use reshape function then number of value will not change but shape will change

array([[3, 3],
       [3, 1],
       [3, 2],
       [3, 3],
       [3, 4],
       [3, 3]])

In [31]:
arr2.reshape(4,3)

array([[3, 3, 3],
       [1, 3, 2],
       [3, 3, 3],
       [4, 3, 3]])

In [32]:
arr2.reshape(4,-1)

array([[3, 3, 3],
       [1, 3, 2],
       [3, 3, 3],
       [4, 3, 3]])

In [34]:
arr2.reshape(4,-1234464826)

array([[3, 3, 3],
       [1, 3, 2],
       [3, 3, 3],
       [4, 3, 3]])

In [35]:
arr2.reshape(2,2,3)

array([[[3, 3, 3],
        [1, 3, 2]],

       [[3, 3, 3],
        [4, 3, 3]]])

In [36]:
arr2.reshape(2,2,3,1,1,1)

array([[[[[[3]]],


         [[[3]]],


         [[[3]]]],



        [[[[1]]],


         [[[3]]],


         [[[2]]]]],




       [[[[[3]]],


         [[[3]]],


         [[[3]]]],



        [[[[4]]],


         [[[3]]],


         [[[3]]]]]])

In [37]:
arr1 = np.random.randint(1,10,(5,6))
arr1

array([[9, 4, 7, 4, 7, 9],
       [7, 4, 7, 1, 2, 6],
       [3, 6, 3, 5, 1, 2],
       [8, 6, 6, 7, 4, 4],
       [9, 8, 3, 7, 6, 9]])

In [38]:
arr1 > 8

array([[ True, False, False, False, False,  True],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [ True, False, False, False, False,  True]])

In [39]:
arr1 [arr1 > 8]

array([9, 9, 9, 9])

In [40]:
arr1

array([[9, 4, 7, 4, 7, 9],
       [7, 4, 7, 1, 2, 6],
       [3, 6, 3, 5, 1, 2],
       [8, 6, 6, 7, 4, 4],
       [9, 8, 3, 7, 6, 9]])

In [41]:
arr1[0,1]

4

In [42]:
arr1[2:4,[2,3]]

array([[3, 5],
       [6, 7]])

In [43]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))
arr1

array([[2, 1, 1],
       [2, 1, 1],
       [2, 1, 1]])

In [44]:
arr2

array([[2, 1, 2],
       [2, 1, 2],
       [1, 2, 2]])

In [45]:
arr1 + arr2

array([[4, 2, 3],
       [4, 2, 3],
       [3, 3, 3]])

In [46]:
arr1 - arr2

array([[ 0,  0, -1],
       [ 0,  0, -1],
       [ 1, -1, -1]])

In [47]:
arr1 * arr2

array([[4, 1, 2],
       [4, 1, 2],
       [2, 2, 2]])

In [48]:
arr1 @ arr2

array([[7, 5, 8],
       [7, 5, 8],
       [7, 5, 8]])

In [49]:
arr1/arr2

array([[1. , 1. , 0.5],
       [1. , 1. , 0.5],
       [2. , 0.5, 0.5]])

In [50]:
arr1/0

C:\Users\LAPTOP\AppData\Local\Temp\ipykernel_14084\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [51]:
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [52]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [53]:
a = np.array([1,2,3,4])
arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [54]:
b= np.array([5,6,7,8])
arr+b.T

array([[5., 6., 7., 8.],
       [5., 6., 7., 8.],
       [5., 6., 7., 8.]])

In [55]:
b.T

array([5, 6, 7, 8])

In [56]:
arr1 = np.array([5,6,7,8])
arr1*arr+b.T

array([[5., 6., 7., 8.],
       [5., 6., 7., 8.],
       [5., 6., 7., 8.]])

In [57]:
b.T

array([5, 6, 7, 8])

In [58]:
arr1

array([5, 6, 7, 8])

In [59]:
np.sqrt(arr1)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712])

In [60]:
np.log10(arr1)

array([0.69897   , 0.77815125, 0.84509804, 0.90308999])

In [62]:
np.exp(arr1)

array([ 148.4131591 ,  403.42879349, 1096.63315843, 2980.95798704])